global:
  domain: argocd.nieradko.com

server:
  ingress:
    enabled: true
    ingressClassName: nginx
    annotations:
      cert-manager.io/cluster-issuer: letsencrypt-prod
      nginx.ingress.kubernetes.io/ssl-passthrough: "true"
      nginx.ingress.kubernetes.io/backend-protocol: "HTTPS"
    extraTls:
      - hosts:
          - argocd.nieradko.com
        secretName: argocd-tls

configs:
  cm:
    accounts.kanareklife: login
  rbac:
    policy.default: role:user
    policy.csv: |
      p, role:user, applications, get, *, allow
      p, role:user, applications, sync, *, allow
      p, role:user, applicationsets, get, *, allow
      p, role:user, clusters, get, *, allow
      p, role:user, repositories, get, *, allow
      p, role:user, logs, get, *, allow
      p, role:user, projects, get, *, allow
      g, kanareklife, role:user
      g, admin, role:admin
