apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: argocd-manifests
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://github.com/KanarekLife/cloud.nieradko.com.git
    targetRevision: main
    path: kubernetes/argocd/manifests
    directory:
      recurse: true
  destination:
    name: in-cluster
    namespace: argocd
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
