apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: longhorn
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: infra
  sources:
    - repoURL: https://charts.longhorn.io
      chart: longhorn
      targetRevision: v1.9.1
      helm:
        valueFiles:
          - $values/kubernetes/longhorn/values.yml
    - repoURL: https://github.com/KanarekLife/cloud.nieradko.com
      targetRevision: main
      ref: values
  destination:
    name: in-cluster
    namespace: longhorn-system
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
